### ISSUE TITLE
Sync Tool 3.1

### ISSUE THREAD

**Issue by adilem** [vnsur/aapanel-v7-lifetime#1]
thank you for your work
can you fix this please

Sync Tool 3.1

![Ekran görüntüsü 2024-07-01 215850](https://github.com/vnsur/aapanel-v7-lifetime/assets/47526212/090a92c8-86de-41cb-affd-2d2e3a0fbd9a)

**Comment by adilem** [comment]
v7.0.5 is installed normally old version update notification is coming as I showed in the picture please fix this please do not notify for low version

![Ekran görüntüsü 2024-07-01 222130](https://github.com/vnsur/aapanel-v7-lifetime/assets/47526212/071f0312-a0df-4cce-b3f2-e87c5cb00499)

**Comment by vnsur** [comment]
After installation, please operate the key combination
CTRL + F5

or ssh access
bt -> 9

**Comment by adilem** [comment]
> After installation, please operate the key combination CTRL + F5
> 
> or ssh access bt -> 9
I did a new installation and it's the same again, I found another error and now I'm sending them, I hope I'm not bothering you.

If you load the places I showed visually in picture 1, the error with picture 2 comes out, I said for information purposes.
![1](https://github.com/vnsur/aapanel-v7-lifetime/assets/47526212/6d8abff9-dabe-4a9c-9544-82aba549f9ae)


![2](https://github.com/vnsur/aapanel-v7-lifetime/assets/47526212/7c7dcb75-42d7-4050-80bf-d3bfeb388047)

**Comment by adilem** [comment]
now I did a clean install on ubuntu 20.04 and got the same old version notification again

![new](https://github.com/vnsur/aapanel-v7-lifetime/assets/47526212/fbb213ee-df4c-4fa6-8b6a-f70c2e5abb47)

**Comment by adilem** [comment]
I accepted the incoming old version notification, installed the old version, then clicked update again and said update to the new version, this time it happened 

but I sent other pictures and the bugs are still there, I hope you can fix them.

**Comment by vnsur** [comment]
Uninstall Sync Tool 3.1 and reinstall again, -> fixed

**Comment by adilem** [comment]
> Uninstall Sync Tool 3.1 and reinstall again, -> fixed
yes it worked now thank you very much

now I did the installation on clean ubuntu and I noticed that if I update from the panel, the original /www/server/panel/class/panelPlugin.py installs, this plugin does not install, I installed the plugin from the panel update, so I installed the plugin that way

![Ekran görüntüsü 2024-07-02 133249](https://github.com/vnsur/aapanel-v7-lifetime/assets/47526212/c0dc89be-7de9-488b-8186-e91d2f6ff0c9)
![Ekran görüntüsü 2024-07-02 133930](https://github.com/vnsur/aapanel-v7-lifetime/assets/47526212/dbf64dd1-1ad7-4dbd-ae5e-345c9e0755a8)

![Ekran görüntüsü 2024-07-02 134206](https://github.com/vnsur/aapanel-v7-lifetime/assets/47526212/fc44cd2e-bcc3-46ea-bc12-17537c115b0f)

**Comment by adilem** [comment]
aaPanel 7.0.6   new version just released

![Ekran görüntüsü 2024-07-02 145917](https://github.com/vnsur/aapanel-v7-lifetime/assets/47526212/d373ead3-3977-41ad-a062-ee5970b2cc45)

**Comment by vnsur** [comment]
> aaPanel 7.0.6 new version just released
> 
> ![Ekran görüntüsü 2024-07-02 145917](https://private-user-images.githubusercontent.com/47526212/345013850-d373ead3-3977-41ad-a062-ee5970b2cc45.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzU1MTAsIm5iZiI6MTcxOTk3NTIxMCwicGF0aCI6Ii80NzUyNjIxMi8zNDUwMTM4NTAtZDM3M2VhZDMtMzk3Ny00MWFkLWEwNjItZWU1OTcwYjJjYzQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDAyNTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTE1ODFkNDdiZGNjMTgyMTJhZWNjNjRmYmU5MTJiZmU3NmZkNzQ1YjMwMDBhYTQwNWJmZjRlOTIyYTEyOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPbtxXW4RTrqJdvbXAzD7p6fUVyYDx_L5aZr7zllN70)

Once you achieve stability, you should maintain it, never run after something new with instability

**Comment by adilem** [comment]
> > aaPanel 7.0.6 new version just released
> > ![Ekran görüntüsü 2024-07-02 145917](https://private-user-images.githubusercontent.com/47526212/345013850-d373ead3-3977-41ad-a062-ee5970b2cc45.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzU1MTAsIm5iZiI6MTcxOTk3NTIxMCwicGF0aCI6Ii80NzUyNjIxMi8zNDUwMTM4NTAtZDM3M2VhZDMtMzk3Ny00MWFkLWEwNjItZWU1OTcwYjJjYzQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDAyNTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTE1ODFkNDdiZGNjMTgyMTJhZWNjNjRmYmU5MTJiZmU3NmZkNzQ1YjMwMDBhYTQwNWJmZjRlOTIyYTEyOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPbtxXW4RTrqJdvbXAzD7p6fUVyYDx_L5aZr7zllN70)
> 
> Once you achieve stability, you should maintain it, never run after something new with instability

Yes you are right you said a very correct word, then if there are deficiencies or bugs we see, let's focus on them and we will use a fully stable version.

**Comment by vnsur** [comment]
Completed problem solving

**Comment by adilem** [comment]
> Completed problem solving

7.0.6  seems more stable and runs faster than other versions

> > Kurulumdan sonra lütfen CTRL + F5 tuş kombinasyonunu kullanın
> > veya ssh access bt -> 9 
> > Yeni bir kurulum yaptım ve yine aynı, bir hata daha buldum ve şimdi gönderiyorum, umarım sizi rahatsız etmiyorumdur.
> 
> Resim 1'de görsel olarak gösterdiğim yerleri yüklerseniz resim 2'deki hata çıkıyor, bilgilendirme amaçlı söyledim. ![1](https://private-user-images.githubusercontent.com/47526212/344843374-6d8abff9-dabe-4a9c-9544-82aba549f9ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODg2MDQsIm5iZiI6MTcxOTk4ODMwNCwicGF0aCI6Ii80NzUyNjIxMi8zNDQ4NDMzNzQtNmQ4YWJmZjktZGFiZS00YTljLTk1NDQtODJhYmE1NDlmOWFlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA2MzE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NDdiNmUyOGNmNWQwMDFlYzZkYjdiODNiZDE4ODc0YzUwNTlhOWQzOWUzOTkxOGJkZmEyYzhmZTg1ZjIzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qGa-HGLLnH-FNfWdt3RRiPR8bw2i7DNFwOZCWBdmMFo)
> 
> ![2](https://private-user-images.githubusercontent.com/47526212/344843397-7c7dcb75-42d7-4050-80bf-d3bfeb388047.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODg2MDQsIm5iZiI6MTcxOTk4ODMwNCwicGF0aCI6Ii80NzUyNjIxMi8zNDQ4NDMzOTctN2M3ZGNiNzUtNDJkNy00MDUwLTgwYmYtZDNiZmViMzg4MDQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA2MzE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkN2IwMDlhZjBlOWIyZDY1ZWNiYTZkOTNjOWFlOGNjMDk1ZGQyOWQ3ZDc3ODM0NmQyMDg4MTE1NmFmZDE1NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xspQNi0suhj_bGY3td5FGNNJl_gUUgKv22vf760-rLA)

Is it possible to solve the problems that arise here?
seems more stable and runs faster than other versions ,7.0.6
