### ISSUE TITLE
a working panel crashes when I install this

### ISSUE THREAD

**Issue by adilem** [vnsur/aapanel-v7-lifetime#4]
a working panel crashes when I install this

Switch to CRACK mode:

curl https://bt.maxcdn.top/install/update_7.x_en.sh|bash

**Comment by vnsur** [comment]
Please describe the specific problem

**Comment by adilem** [comment]
I did the first free installation of the original version
I installed your version of it, the panel interface never came back, I had to install it from scratch again.

**Comment by vnsur** [comment]
Specifically, which version did you install the free version?
and after you run my script, the error is that you can't access the panel at public IP or ssh?

**Comment by vnsur** [comment]
Because I'm still running it personally and my clients are running fine on almalinux 8 and ubuntu 20.04.

Because currently I do not support individual installation. If you want installation support, I will charge a fee
It is expected that I will not support updates to future versions

**Comment by adilem** [comment]
Install aaPanel 7.0.6 I installed this version first from the original website
I am using this version 20.04
When I did it this way, the panel is now impossible for me to reach.
then I installed the version you did so on it Switch to CRACK mode:
I'm accessing ssh only panel access is going 
curl https://bt.maxcdn.top/install/update_7.x_en.sh|bash

**Comment by adilem** [comment]
install the original panel and then install your version on this version and you will see the error

Switch to CRACK mode:

curl https://bt.maxcdn.top/install/update_7.x_en.sh|bash

**Comment by vnsur** [comment]
let me close this repositories, because it is not complete for all users

**Comment by vnsur** [comment]
lose

**Comment by vnsur** [comment]
close

**Comment by adilem** [comment]
ok you can close it thank you very much for everything
